### ISSUE TITLE
Crash zoom-out with 1.3.6 version

### ISSUE THREAD

**Issue by developerGM** [smarteist/Android-Image-Slider#130]
After update to 1.3.6 version and using "false" as second params in adapter, during zoom out I have this crash:

```
2020-05-07 16:16:26.242 8705-8705/com.xxx E/RecyclerView: No adapter attached; skipping layout
2020-05-07 16:16:39.015 8705-8705/com.xxx E/MotionEvent-JNI: validatePointerIndex pointerIndex:-1, pointerCount:1
2020-05-07 16:16:39.017 8705-8705/com.xxx E/InputEventReceiver: Exception dispatching input event.
2020-05-07 16:16:39.020 8705-8705/com.xxx E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxx, PID: 8705
    java.lang.IllegalArgumentException: pointerIndex out of range
        at android.view.MotionEvent.nativeGetAxisValue(Native Method)
        at android.view.MotionEvent.getX(MotionEvent.java:2122)
        at com.smarteist.autoimageslider.SliderPager.onInterceptTouchEvent(SliderPager.java:2073)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2247)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:439)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1839)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3080)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:401)
        at android.view.View.dispatchPointerEvent(View.java:10293)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4968)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4792)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4298)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4351)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4317)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4464)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4325)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4521)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4298)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4351)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4317)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4325)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4298)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6857)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6831)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6774)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7029)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6988)
        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7055)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:907)
        at android.view.Choreographer.doCallbacks(Choreographer.java:709)
2020-05-07 16:16:39.020 8705-8705/com.xxx E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:638)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6255)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

**Comment by smarteist** [comment]
this is a bug in slider pager , thanks for reporting. library updated.

**Comment by developerGM** [comment]
thanks for your support smarteist.
So, will we wait 1.3.7 release?

**Comment by smarteist** [comment]
> thanks for your support smarteist.
> So, will we wait 1.3.7 release?

yes now updated.

**Comment by developerGM** [comment]
Confirm, bug fixed. Thank you

**Comment by Poissac9** [comment]
I facing this issue on 1.4.0, how can i fix it 

Error Log:
java.lang.IllegalArgumentException: pointerIndex out of range
	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
	at android.view.MotionEvent.getX(MotionEvent.java:2608)
	at androidx.viewpager.widget.ViewPager.onInterceptTouchEvent(ViewPager.java:2072)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2753)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:749)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1880)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3489)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:707)
	at android.view.View.dispatchPointerEvent(View.java:13732)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6172)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5950)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5399)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5452)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5418)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5577)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5426)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5634)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5399)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5452)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5418)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5426)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5399)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8464)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8384)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8337)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8579)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:198)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:187)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8538)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8606)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:690)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7124)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
