### ISSUE TITLE
Error when slide to left and right from start and end position. 

### ISSUE THREAD

**Issue by alpine12** [smarteist/Android-Image-Slider#49]
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.viewpager.widget.ViewPager.setCurrentItem(int)' on a null object reference
        at com.smarteist.autoimageslider.CircularSliderHandle.onPageScrollStateChanged(CircularSliderHandle.java:37)

**Comment by nayrban** [comment]
I have the same issue

**Comment by pratikbutani** [comment]
Any update on this? I am getting same issue.

Here is the log:

```
 java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.viewpager.widget.ViewPager.setCurrentItem(int)' on a null object reference
        at com.smarteist.autoimageslider.CircularSliderHandle.onPageScrollStateChanged(CircularSliderHandle.java:37)
        at androidx.viewpager.widget.ViewPager.dispatchOnScrollStateChanged(ViewPager.java:1964)
        at androidx.viewpager.widget.ViewPager.setScrollState(ViewPager.java:497)
        at androidx.viewpager.widget.ViewPager.smoothScrollTo(ViewPager.java:976)
        at androidx.viewpager.widget.ViewPager.scrollToItem(ViewPager.java:684)
        at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:670)
        at androidx.viewpager.widget.ViewPager.onTouchEvent(ViewPager.java:2263)
        at android.view.View.dispatchTouchEvent(View.java:12513)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3024)
```

**Comment by AbelJoshua** [comment]
I have the same issue....

**Comment by smarteist** [comment]
Hi! it's now fixed , clean and rebuild your project.

**Comment by pratikbutani** [comment]
Still I am getting same issue.

**Comment by smarteist** [comment]
> Still I am getting same issue.
> 
> Even I removed dependency first and added again but not working.

Restart AndroidStudio using the “Invalidate Cache” option and rebuild the project

**Comment by pratikbutani** [comment]
> > Still I am getting same issue.
> > Even I removed dependency first and added again but not working.
> 
> Restart AndroidStudio using the “Invalidate Cache” option and rebuild the project

Everything I have done, 

I also removed once whole library (wherever I used it) and again I added but not working.

**Comment by pratikbutani** [comment]
By deleting `.cache` folder its working now. Thank you.

**Comment by alpine12** [comment]
Thanks. Works after delete cache folder on gradle folder
