### ISSUE TITLE
SliderAdapterVH error 

### ISSUE THREAD

**Issue by Sarthak2601** [smarteist/Android-Image-Slider#69]

**Comment by smarteist** [comment]
Please send logcat and error title , i don'n know what is that error.

**Comment by ChHaseeb30** [comment]
2020-01-11 00:16:33.799 30975-30975/? E/libc: Access denied finding property "persist.vendor.sys.activitylog"
2020-01-11 00:16:42.381 30975-31042/com.example.knowledgebridge E/ion: ioctl c0044901 failed with code -1: Invalid argument
2020-01-11 00:16:44.646 30975-30975/com.example.knowledgebridge E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.knowledgebridge, PID: 30975
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
        at com.example.knowledgebridge.Adapter.SliderAdapterExample.onBindViewHolder(SliderAdapterExample.java:31)
        at com.example.knowledgebridge.Adapter.SliderAdapterExample.onBindViewHolder(SliderAdapterExample.java:15)
        at com.smarteist.autoimageslider.SliderViewAdapter.instantiateItem(SliderViewAdapter.java:37)
        at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1158)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:23381)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6829)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23381)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6829)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23381)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6829)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.cardview.widget.CardView.onMeasure(CardView.java:260)
        at android.view.View.measure(View.java:23381)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6829)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
        at android.view.View.measure(View.java:23381)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6829)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23381)
        at androidx.constraintlayout.widget.ConstraintLayout.internalMeasureChildren(ConstraintLayout.java:1227)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1572)
        at android.view.View.measure(View.java:23381)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6829)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:733)
        at com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:95)
        at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1556)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:803)
        at android.view.View.measure(View.java:23381)
        at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
        at android.view.View.measure(View.java:23381)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6829)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:23381)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6829)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
        at android.view.View.measure(View.java:23381)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6829)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23381)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6829)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
2020-01-11 00:16:44.647 30975-30975/com.example.knowledgebridge E/AndroidRuntime:     at android.view.View.measure(View.java:23381)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6829)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:867)
        at android.view.View.measure(View.java:23381)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2837)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1634)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1929)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1522)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7438)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:965)
        at android.view.Choreographer.doCallbacks(Choreographer.java:777)
        at android.view.Choreographer.doFrame(Choreographer.java:709)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6715)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)

**Comment by smarteist** [comment]
> 2020-01-11 00:16:33.799 30975-30975/? E/libc: Access denied finding property "persist.vendor.sys.activitylog"
> 2020-01-11 00:16:42.381 30975-31042/com.example.knowledgebridge E/ion: ioctl c0044901 failed with code -1: Invalid argument
> 2020-01-11 00:16:44.646 30975-30975/com.example.knowledgebridge E/AndroidRuntime: FATAL EXCEPTION: main
> Process: com.example.knowledgebridge, PID: 30975
> java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
> at com.example.knowledgebridge.Adapter.SliderAdapterExample.onBindViewHolder(SliderAdapterExample.java:31)
> at com.example.knowledgebridge.Adapter.SliderAdapterExample.onBindViewHolder(SliderAdapterExample.java:15)
> at com.smarteist.autoimageslider.SliderViewAdapter.instantiateItem(SliderViewAdapter.java:37)
> at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
> at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1158)
> at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
> at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
> at android.view.View.measure(View.java:23381)
> at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6829)
> at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
> at android.view.View.measure(View.java:23381)
> at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6829)
> at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
> at android.view.View.measure(View.java:23381)
> at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6829)
> at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
> at androidx.cardview.widget.CardView.onMeasure(CardView.java:260)
> at android.view.View.measure(View.java:23381)
> at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6829)
> at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
> at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
> at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
> at android.view.View.measure(View.java:23381)
> at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6829)
> at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
> at android.view.View.measure(View.java:23381)
> at androidx.constraintlayout.widget.ConstraintLayout.internalMeasureChildren(ConstraintLayout.java:1227)
> at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1572)
> at android.view.View.measure(View.java:23381)
> at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6829)
> at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:733)
> at com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:95)
> at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1556)
> at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:803)
> at android.view.View.measure(View.java:23381)
> at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
> at android.view.View.measure(View.java:23381)
> at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6829)
> at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
> at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
> at android.view.View.measure(View.java:23381)
> at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6829)
> at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
> at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
> at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
> at android.view.View.measure(View.java:23381)
> at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6829)
> at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
> at android.view.View.measure(View.java:23381)
> at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6829)
> at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
> at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
> at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
> 2020-01-11 00:16:44.647 30975-30975/com.example.knowledgebridge E/AndroidRuntime: at android.view.View.measure(View.java:23381)
> at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6829)
> at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
> at com.android.internal.policy.DecorView.onMeasure(DecorView.java:867)
> at android.view.View.measure(View.java:23381)
> at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2837)
> at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1634)
> at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1929)
> at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1522)
> at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7438)
> at android.view.Choreographer$CallbackRecord.run(Choreographer.java:965)
> at android.view.Choreographer.doCallbacks(Choreographer.java:777)
> at android.view.Choreographer.doFrame(Choreographer.java:709)
> at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
> at android.os.Handler.handleCallback(Handler.java:873)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> at android.os.Looper.loop(Looper.java:193)
> at android.app.ActivityThread.main(ActivityThread.java:6715)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)

`java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
at` This is the reason. your text view not initialized there.

**Comment by ChHaseeb30** [comment]
How can i place my own pictures in the slider....kindly send me code if
possible
